Added media queries for desktop browser
ntazelo/Portfolio pull request #4
Opened 2021-09-23 16:47 UTC by ntazelo

### In this project

**I added media queries**
**I updated HTML for responsiveness styling**

2021-09-23 17:18 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Eloi Ntazama, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
README is professiona. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-23 17:18 UTC, SajjadAhmad14 commented on style.css
> +@media (min-width: 900px) {
Please write the value for min-width property should in range of 992px - 1100px.

2021-09-23 17:18 UTC, SajjadAhmad14 commented on style.css
> +@media (min-width: 1200px) {
Please write the value for min-width property should in range of 992px - 1100px.

2021-09-23 17:18 UTC, SajjadAhmad14 commented on style.css
> +@media (min-width: 600px) {
Please write the value for min-width property should in range of 992px - 1100px.

2021-09-23 17:18 UTC, SajjadAhmad14 commented on style.css
> +  .intro {
Please use the font color for the Headline section from the design.

2021-09-23 17:18 UTC, SajjadAhmad14 commented on index.html
> +    <section class="about">
Please use the font color for the About me section from the design.

2021-09-24 13:20 UTC, AshakaE approved these changes
### Hi @ntazelo  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the requested changes 👍🏾
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 13:28 UTC, merged